<?php

/**
 * @file
 * Auth0 module.
 */

/**
 * Defines the default JWT leeway.
 */
const AUTH0_JWT_LEEWAY_DEFAULT = 180;

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {
  return [
    'auth0_login' => [
      'template' => 'auth0-login',
      'variables' => [
        'domain' => NULL,
        'clientID' => NULL,
        'state' => NULL,
        'showSignup' => NULL,
        'offlineAccess' => FALSE,
        'widgetCdn' => NULL,
        'loginCSS' => NULL,
        'callbackURL' => NULL,
        'lockExtraSettings' => '{}',
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function auth0_library_info_build() {
  $config = \Drupal::service('config.factory')->get('auth0.settings');
  return [
    'auth0.widget' => [
      'js' => [
        $config->get('auth0_widget_cdn') => [
          'type' => 'external',
        ],
      ],
    ],
  ];
}

/**
 * Handle users deletion, it should delete the auth0 profile.
 */
function auth0_user_delete($account) {
  db_delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}

/**
 * Use Refresh Token
 */
function auth0_signin_with_refresh_token($token) {
  $helper = new AuthHelper();

  return $helper->getUserUsingRefreshToken($token);
}